### ISSUE TITLE
经常用没几次就报错

### ISSUE THREAD

**Issue by huangshixian2023** [adryfish/llm-web-api#2]
2024-06-11 11:54:01,874 - AppLogger - INFO - [OpenAIClient.create_completion] Start chat_completion
2024-06-11 11:54:02,135 - AppLogger - INFO - [OpenAIClient.__handle_route] Write response to page
Error occurred in event listener
Traceback (most recent call last):
  File "E:\huowei\python\test\llm-web-api\llm\provider\openai\client.py", line 126, in __handle_route
    async with self.http_client.stream(
  File "C:\Python312\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpx\_client.py", line 1617, in stream
    response = await self.send(
               ^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 317, in handle_async_request
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpcore\_async\http11.py", line 383, in start_tls
    return await self._stream.start_tls(ssl_context, server_hostname, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 80, in start_tls
    raise exc
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 71, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\anyio\streams\tls.py", line 132, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\anyio\streams\tls.py", line 140, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Python312\Lib\ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\playwright\_impl\_page.py", line 281, in _on_route
    handled = await route_handler.handle(route)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\playwright\_impl\_helper.py", line 290, in handle
    raise e
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\playwright\_impl\_helper.py", line 285, in handle
    return await self._handle_internal(route)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\huowei\python\test\llm-web-api\venv\Lib\site-packages\playwright\_impl\_helper.py", line 318, in _handle_internal
    await asyncio.ensure_future(coro_or_future)
  File "E:\huowei\python\test\llm-web-api\llm\provider\openai\client.py", line 169, in __handle_route
    status=response.status_code,
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

**Comment by adryfish** [comment]
什么环境跑的程序？

**Comment by huangshixian2023** [comment]
win10 Python 3.12.1  按介绍里的说明一步一步操作 经常是成功几个 然后就会报这个错误 得关掉重新再运行 在运行几个成功在报错 一直循环

**Comment by adryfish** [comment]
你再试一下最新的，怀疑是可能校验TLS指纹，已经将httpx移除，使用Javascript Fetch API。

**Comment by huangshixian2023** [comment]
报错是没有了 但是 运行多了会有这提示You've reached our limit of messages per hour. Please try again later.
用的模型是gpt-3.5-turbo

**Comment by adryfish** [comment]
是用什么请求的？curl还是chatgpt-web这种客户端？如果是用客户端，先用curl试一下，可以访问则说明是客户端的问题。

**Comment by huangshixian2023** [comment]
就用咱们这个llm-web-api去访问的 大概 30几次 后提示，我新开浏览器访问gpt可以正常使用

**Comment by adryfish** [comment]
有llm-web-api报错的错误堆栈吗？

**Comment by huangshixian2023** [comment]
[32mINFO[0m:     Started server process [[36m28276[0m]
[32mINFO[0m:     Waiting for application startup.
2024-06-17 16:37:57,286 - AppLogger - INFO - [OpenAILogin.begin] OpenAILogin start...
2024-06-17 16:37:57,450 - AppLogger - INFO - [OpenAILogin.begin] OpenAILogin finished...
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2024-06-17 16:38:10,291 - AppLogger - INFO - [OpenAIClient.create_completion] Start chat_completion
2024-06-17 16:38:10,916 - AppLogger - ERROR - [OpenAIClient.__handle_route] HTTP request failed. status: 429. message: {"detail":"You've reached our limit of messages per hour. Please try again later."}  就不动了 换了IP也没用我在想要不要 注册个邮箱登入 匿名的情况下出现的

**Comment by adryfish** [comment]
这个是OpenAI官方做的限制，它限制的单IP最大请求数。另外，换IP是可以的，你需要清除上一个IP访问的browser_data。

**Comment by huangshixian2023** [comment]
好的谢啦
